class Statement{
}
Statement  <|--  Assignement
Statement  <|--  VarDecl
class Assignement{
}
Assignement  -->  $container Model<IdentifierObject>
Assignement  -->  left VarRef<IdentifierObject>
Assignement  -->  value number
class Model{
}
Model  -->  statements Array<Statement>
class VarDecl{
}
VarDecl  -->  $container Model<IdentifierObject>
VarDecl  -->  name string
class VarRef{
}
VarRef  -->  $container Assignement<IdentifierObject>
VarRef  -->  ref Reference<VarDecl>