import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { MyLanguageGeneratedModule, MyLanguageGeneratedSharedModule } from './generated/module.js';
import { MyLanguageValidator, registerValidationChecks } from './my-language-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type MyLanguageAddedServices = {
    validation: {
        MyLanguageValidator: MyLanguageValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type MyLanguageServices = LangiumServices & MyLanguageAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const MyLanguageModule: Module<MyLanguageServices, PartialLangiumServices & MyLanguageAddedServices> = {
    validation: {
        MyLanguageValidator: () => new MyLanguageValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createMyLanguageServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    MyLanguage: MyLanguageServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        MyLanguageGeneratedSharedModule
    );
    const MyLanguage = inject(
        createDefaultModule({ shared }),
        MyLanguageGeneratedModule,
        MyLanguageModule
    );
    shared.ServiceRegistry.register(MyLanguage);
    registerValidationChecks(MyLanguage);
    return { shared, MyLanguage };
}
