@startuml mydiag

class Statement{
}
Statement <|-- VarDecl 
Statement <|-- Assignement
VarDecl -[hidden]> Assignement

class Assignement {
  value: number
}
Assignement "container\n1" *-- "left\n1" VarRef

class Model {
}
Model "container\n1" *--> "statements\n0..*" Statement


class VarDecl {
  name: string
}

class VarRef {
}
VarRef --> "reference\n1" VarDecl
@enduml 
