@startuml mydiag

class Model {
}

class Statement{
}

class VarDecl {
  name: string
}

class VarRef {
}

class Assignement {
  value: number
}

Statement <|-- VarDecl
Statement <|-- Assignement
VarDecl -[hidden]> Assignement
Assignement "container\n1" *-- "left\n1" VarRef
Model "container\n1" *--> "statements\n0..*" Statement
VarRef --> "reference\n1" VarDecl
@enduml 
